project_id = "wuieuiohusgfdilemplj"

[functions.sync-synnex]
verify_jwt = false

[functions.save-products]
verify_jwt = true


[functions.send-newsletter-welcome]
verify_jwt = false

[functions.shopee-oauth-authorize]
verify_jwt = true

[functions.shopee-oauth-callback]
verify_jwt = false

[functions.shopee-test-connection]
verify_jwt = true

[functions.ginee-list-shops]
verify_jwt = true

[functions.ginee-sync-products]
verify_jwt = true
