/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingInfoRouteImport } from './routes/shipping-info'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PcBuilderRouteImport } from './routes/pc-builder'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as HowToOrderRouteImport } from './routes/how-to-order'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreditApplicationIndexRouteImport } from './routes/credit-application.index'
import { Route as TrackOrderNumberRouteImport } from './routes/track.$orderNumber'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as CreditApplicationSuccessRouteImport } from './routes/credit-application.success'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedMyOrdersRouteImport } from './routes/_authenticated/my-orders'
import { Route as AuthenticatedMyAccountRouteImport } from './routes/_authenticated/my-account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMyAccountIndexRouteImport } from './routes/_authenticated/my-account.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedMyAccountProfileRouteImport } from './routes/_authenticated/my-account.profile'
import { Route as AuthenticatedMyAccountPaymentRouteImport } from './routes/_authenticated/my-account.payment'
import { Route as AuthenticatedMyAccountOrdersRouteImport } from './routes/_authenticated/my-account.orders'
import { Route as AuthenticatedMyAccountMembershipRouteImport } from './routes/_authenticated/my-account.membership'
import { Route as AuthenticatedMyAccountCreditRouteImport } from './routes/_authenticated/my-account.credit'
import { Route as AuthenticatedMyAccountCompanyRouteImport } from './routes/_authenticated/my-account.company'
import { Route as AuthenticatedMyAccountAddressesRouteImport } from './routes/_authenticated/my-account.addresses'
import { Route as AuthenticatedAdminSyncRouteImport } from './routes/_authenticated/admin.sync'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminPurchaseOrdersRouteImport } from './routes/_authenticated/admin.purchase-orders'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin.newsletter'
import { Route as AuthenticatedAdminFlashDealsRouteImport } from './routes/_authenticated/admin.flash-deals'
import { Route as AuthenticatedAdminDistributorContactsRouteImport } from './routes/_authenticated/admin.distributor-contacts'
import { Route as AuthenticatedAdminDiscountCodesRouteImport } from './routes/_authenticated/admin.discount-codes'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCreditApplicationsRouteImport } from './routes/_authenticated/admin.credit-applications'
import { Route as AuthenticatedAdminCreditRouteImport } from './routes/_authenticated/admin.credit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminPurchaseOrdersPoIdRouteImport } from './routes/_authenticated/admin.purchase-orders_.$poId'
import { Route as AuthenticatedAdminPricingProductsRouteImport } from './routes/_authenticated/admin.pricing.products'
import { Route as AuthenticatedAdminPricingAuditRouteImport } from './routes/_authenticated/admin.pricing.audit'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated/admin.orders.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingInfoRoute = ShippingInfoRouteImport.update({
  id: '/shipping-info',
  path: '/shipping-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PcBuilderRoute = PcBuilderRouteImport.update({
  id: '/pc-builder',
  path: '/pc-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToOrderRoute = HowToOrderRouteImport.update({
  id: '/how-to-order',
  path: '/how-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditApplicationIndexRoute = CreditApplicationIndexRouteImport.update({
  id: '/credit-application/',
  path: '/credit-application/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderNumberRoute = TrackOrderNumberRouteImport.update({
  id: '/track/$orderNumber',
  path: '/track/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditApplicationSuccessRoute =
  CreditApplicationSuccessRouteImport.update({
    id: '/credit-application/success',
    path: '/credit-application/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedMyOrdersRoute = AuthenticatedMyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAccountRoute = AuthenticatedMyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAccountIndexRoute =
  AuthenticatedMyAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMyAccountProfileRoute =
  AuthenticatedMyAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedMyAccountPaymentRoute =
  AuthenticatedMyAccountPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedMyAccountOrdersRoute =
  AuthenticatedMyAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedMyAccountMembershipRoute =
  AuthenticatedMyAccountMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedMyAccountCreditRoute =
  AuthenticatedMyAccountCreditRouteImport.update({
    id: '/credit',
    path: '/credit',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedMyAccountCompanyRoute =
  AuthenticatedMyAccountCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedMyAccountAddressesRoute =
  AuthenticatedMyAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedMyAccountRoute,
  } as any)
const AuthenticatedAdminSyncRoute = AuthenticatedAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPurchaseOrdersRoute =
  AuthenticatedAdminPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFlashDealsRoute =
  AuthenticatedAdminFlashDealsRouteImport.update({
    id: '/flash-deals',
    path: '/flash-deals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDistributorContactsRoute =
  AuthenticatedAdminDistributorContactsRouteImport.update({
    id: '/distributor-contacts',
    path: '/distributor-contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiscountCodesRoute =
  AuthenticatedAdminDiscountCodesRouteImport.update({
    id: '/discount-codes',
    path: '/discount-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCreditApplicationsRoute =
  AuthenticatedAdminCreditApplicationsRouteImport.update({
    id: '/credit-applications',
    path: '/credit-applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCreditRoute =
  AuthenticatedAdminCreditRouteImport.update({
    id: '/credit',
    path: '/credit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPurchaseOrdersPoIdRoute =
  AuthenticatedAdminPurchaseOrdersPoIdRouteImport.update({
    id: '/purchase-orders_/$poId',
    path: '/purchase-orders/$poId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPricingProductsRoute =
  AuthenticatedAdminPricingProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminPricingRoute,
  } as any)
const AuthenticatedAdminPricingAuditRoute =
  AuthenticatedAdminPricingAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAdminPricingRoute,
  } as any)
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/how-to-order': typeof HowToOrderRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/pc-builder': typeof PcBuilderRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping-info': typeof ShippingInfoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-account': typeof AuthenticatedMyAccountRouteWithChildren
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/credit-application/success': typeof CreditApplicationSuccessRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/track/$orderNumber': typeof TrackOrderNumberRoute
  '/credit-application/': typeof CreditApplicationIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/credit': typeof AuthenticatedAdminCreditRoute
  '/admin/credit-applications': typeof AuthenticatedAdminCreditApplicationsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/discount-codes': typeof AuthenticatedAdminDiscountCodesRoute
  '/admin/distributor-contacts': typeof AuthenticatedAdminDistributorContactsRoute
  '/admin/flash-deals': typeof AuthenticatedAdminFlashDealsRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/pricing': typeof AuthenticatedAdminPricingRouteWithChildren
  '/admin/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/my-account/addresses': typeof AuthenticatedMyAccountAddressesRoute
  '/my-account/company': typeof AuthenticatedMyAccountCompanyRoute
  '/my-account/credit': typeof AuthenticatedMyAccountCreditRoute
  '/my-account/membership': typeof AuthenticatedMyAccountMembershipRoute
  '/my-account/orders': typeof AuthenticatedMyAccountOrdersRoute
  '/my-account/payment': typeof AuthenticatedMyAccountPaymentRoute
  '/my-account/profile': typeof AuthenticatedMyAccountProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/my-account/': typeof AuthenticatedMyAccountIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/pricing/audit': typeof AuthenticatedAdminPricingAuditRoute
  '/admin/pricing/products': typeof AuthenticatedAdminPricingProductsRoute
  '/admin/purchase-orders/$poId': typeof AuthenticatedAdminPurchaseOrdersPoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/how-to-order': typeof HowToOrderRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/pc-builder': typeof PcBuilderRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping-info': typeof ShippingInfoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/credit-application/success': typeof CreditApplicationSuccessRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/track/$orderNumber': typeof TrackOrderNumberRoute
  '/credit-application': typeof CreditApplicationIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/credit': typeof AuthenticatedAdminCreditRoute
  '/admin/credit-applications': typeof AuthenticatedAdminCreditApplicationsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/discount-codes': typeof AuthenticatedAdminDiscountCodesRoute
  '/admin/distributor-contacts': typeof AuthenticatedAdminDistributorContactsRoute
  '/admin/flash-deals': typeof AuthenticatedAdminFlashDealsRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/pricing': typeof AuthenticatedAdminPricingRouteWithChildren
  '/admin/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/my-account/addresses': typeof AuthenticatedMyAccountAddressesRoute
  '/my-account/company': typeof AuthenticatedMyAccountCompanyRoute
  '/my-account/credit': typeof AuthenticatedMyAccountCreditRoute
  '/my-account/membership': typeof AuthenticatedMyAccountMembershipRoute
  '/my-account/orders': typeof AuthenticatedMyAccountOrdersRoute
  '/my-account/payment': typeof AuthenticatedMyAccountPaymentRoute
  '/my-account/profile': typeof AuthenticatedMyAccountProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/my-account': typeof AuthenticatedMyAccountIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/pricing/audit': typeof AuthenticatedAdminPricingAuditRoute
  '/admin/pricing/products': typeof AuthenticatedAdminPricingProductsRoute
  '/admin/purchase-orders/$poId': typeof AuthenticatedAdminPurchaseOrdersPoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/how-to-order': typeof HowToOrderRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/pc-builder': typeof PcBuilderRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping-info': typeof ShippingInfoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/my-account': typeof AuthenticatedMyAccountRouteWithChildren
  '/_authenticated/my-orders': typeof AuthenticatedMyOrdersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/credit-application/success': typeof CreditApplicationSuccessRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/track/$orderNumber': typeof TrackOrderNumberRoute
  '/credit-application/': typeof CreditApplicationIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/credit': typeof AuthenticatedAdminCreditRoute
  '/_authenticated/admin/credit-applications': typeof AuthenticatedAdminCreditApplicationsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/discount-codes': typeof AuthenticatedAdminDiscountCodesRoute
  '/_authenticated/admin/distributor-contacts': typeof AuthenticatedAdminDistributorContactsRoute
  '/_authenticated/admin/flash-deals': typeof AuthenticatedAdminFlashDealsRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRouteWithChildren
  '/_authenticated/admin/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/_authenticated/my-account/addresses': typeof AuthenticatedMyAccountAddressesRoute
  '/_authenticated/my-account/company': typeof AuthenticatedMyAccountCompanyRoute
  '/_authenticated/my-account/credit': typeof AuthenticatedMyAccountCreditRoute
  '/_authenticated/my-account/membership': typeof AuthenticatedMyAccountMembershipRoute
  '/_authenticated/my-account/orders': typeof AuthenticatedMyAccountOrdersRoute
  '/_authenticated/my-account/payment': typeof AuthenticatedMyAccountPaymentRoute
  '/_authenticated/my-account/profile': typeof AuthenticatedMyAccountProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/my-account/': typeof AuthenticatedMyAccountIndexRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/_authenticated/admin/pricing/audit': typeof AuthenticatedAdminPricingAuditRoute
  '/_authenticated/admin/pricing/products': typeof AuthenticatedAdminPricingProductsRoute
  '/_authenticated/admin/purchase-orders_/$poId': typeof AuthenticatedAdminPurchaseOrdersPoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/corporate'
    | '/how-to-order'
    | '/payment-methods'
    | '/pc-builder'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/shipping-info'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/admin'
    | '/my-account'
    | '/my-orders'
    | '/auth/callback'
    | '/credit-application/success'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/track/$orderNumber'
    | '/credit-application/'
    | '/admin/analytics'
    | '/admin/credit'
    | '/admin/credit-applications'
    | '/admin/customers'
    | '/admin/discount-codes'
    | '/admin/distributor-contacts'
    | '/admin/flash-deals'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/purchase-orders'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/sync'
    | '/my-account/addresses'
    | '/my-account/company'
    | '/my-account/credit'
    | '/my-account/membership'
    | '/my-account/orders'
    | '/my-account/payment'
    | '/my-account/profile'
    | '/admin/'
    | '/my-account/'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/pricing/audit'
    | '/admin/pricing/products'
    | '/admin/purchase-orders/$poId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/corporate'
    | '/how-to-order'
    | '/payment-methods'
    | '/pc-builder'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/shipping-info'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/my-orders'
    | '/auth/callback'
    | '/credit-application/success'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/track/$orderNumber'
    | '/credit-application'
    | '/admin/analytics'
    | '/admin/credit'
    | '/admin/credit-applications'
    | '/admin/customers'
    | '/admin/discount-codes'
    | '/admin/distributor-contacts'
    | '/admin/flash-deals'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/purchase-orders'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/sync'
    | '/my-account/addresses'
    | '/my-account/company'
    | '/my-account/credit'
    | '/my-account/membership'
    | '/my-account/orders'
    | '/my-account/payment'
    | '/my-account/profile'
    | '/admin'
    | '/my-account'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/pricing/audit'
    | '/admin/pricing/products'
    | '/admin/purchase-orders/$poId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/corporate'
    | '/how-to-order'
    | '/payment-methods'
    | '/pc-builder'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/shipping-info'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/_authenticated/my-account'
    | '/_authenticated/my-orders'
    | '/auth/callback'
    | '/credit-application/success'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/track/$orderNumber'
    | '/credit-application/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/credit'
    | '/_authenticated/admin/credit-applications'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/discount-codes'
    | '/_authenticated/admin/distributor-contacts'
    | '/_authenticated/admin/flash-deals'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/purchase-orders'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sync'
    | '/_authenticated/my-account/addresses'
    | '/_authenticated/my-account/company'
    | '/_authenticated/my-account/credit'
    | '/_authenticated/my-account/membership'
    | '/_authenticated/my-account/orders'
    | '/_authenticated/my-account/payment'
    | '/_authenticated/my-account/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/my-account/'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/orders/$id'
    | '/_authenticated/admin/pricing/audit'
    | '/_authenticated/admin/pricing/products'
    | '/_authenticated/admin/purchase-orders_/$poId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  HowToOrderRoute: typeof HowToOrderRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PcBuilderRoute: typeof PcBuilderRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingInfoRoute: typeof ShippingInfoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  CreditApplicationSuccessRoute: typeof CreditApplicationSuccessRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
  TrackOrderNumberRoute: typeof TrackOrderNumberRoute
  CreditApplicationIndexRoute: typeof CreditApplicationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-info': {
      id: '/shipping-info'
      path: '/shipping-info'
      fullPath: '/shipping-info'
      preLoaderRoute: typeof ShippingInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc-builder': {
      id: '/pc-builder'
      path: '/pc-builder'
      fullPath: '/pc-builder'
      preLoaderRoute: typeof PcBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-order': {
      id: '/how-to-order'
      path: '/how-to-order'
      fullPath: '/how-to-order'
      preLoaderRoute: typeof HowToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-application/': {
      id: '/credit-application/'
      path: '/credit-application'
      fullPath: '/credit-application/'
      preLoaderRoute: typeof CreditApplicationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderNumber': {
      id: '/track/$orderNumber'
      path: '/track/$orderNumber'
      fullPath: '/track/$orderNumber'
      preLoaderRoute: typeof TrackOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-application/success': {
      id: '/credit-application/success'
      path: '/credit-application/success'
      fullPath: '/credit-application/success'
      preLoaderRoute: typeof CreditApplicationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/my-orders': {
      id: '/_authenticated/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof AuthenticatedMyOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-account': {
      id: '/_authenticated/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof AuthenticatedMyAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-account/': {
      id: '/_authenticated/my-account/'
      path: '/'
      fullPath: '/my-account/'
      preLoaderRoute: typeof AuthenticatedMyAccountIndexRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/my-account/profile': {
      id: '/_authenticated/my-account/profile'
      path: '/profile'
      fullPath: '/my-account/profile'
      preLoaderRoute: typeof AuthenticatedMyAccountProfileRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/my-account/payment': {
      id: '/_authenticated/my-account/payment'
      path: '/payment'
      fullPath: '/my-account/payment'
      preLoaderRoute: typeof AuthenticatedMyAccountPaymentRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/my-account/orders': {
      id: '/_authenticated/my-account/orders'
      path: '/orders'
      fullPath: '/my-account/orders'
      preLoaderRoute: typeof AuthenticatedMyAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/my-account/membership': {
      id: '/_authenticated/my-account/membership'
      path: '/membership'
      fullPath: '/my-account/membership'
      preLoaderRoute: typeof AuthenticatedMyAccountMembershipRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/my-account/credit': {
      id: '/_authenticated/my-account/credit'
      path: '/credit'
      fullPath: '/my-account/credit'
      preLoaderRoute: typeof AuthenticatedMyAccountCreditRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/my-account/company': {
      id: '/_authenticated/my-account/company'
      path: '/company'
      fullPath: '/my-account/company'
      preLoaderRoute: typeof AuthenticatedMyAccountCompanyRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/my-account/addresses': {
      id: '/_authenticated/my-account/addresses'
      path: '/addresses'
      fullPath: '/my-account/addresses'
      preLoaderRoute: typeof AuthenticatedMyAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedMyAccountRoute
    }
    '/_authenticated/admin/sync': {
      id: '/_authenticated/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AuthenticatedAdminSyncRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/purchase-orders': {
      id: '/_authenticated/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AuthenticatedAdminPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/flash-deals': {
      id: '/_authenticated/admin/flash-deals'
      path: '/flash-deals'
      fullPath: '/admin/flash-deals'
      preLoaderRoute: typeof AuthenticatedAdminFlashDealsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/distributor-contacts': {
      id: '/_authenticated/admin/distributor-contacts'
      path: '/distributor-contacts'
      fullPath: '/admin/distributor-contacts'
      preLoaderRoute: typeof AuthenticatedAdminDistributorContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/discount-codes': {
      id: '/_authenticated/admin/discount-codes'
      path: '/discount-codes'
      fullPath: '/admin/discount-codes'
      preLoaderRoute: typeof AuthenticatedAdminDiscountCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/credit-applications': {
      id: '/_authenticated/admin/credit-applications'
      path: '/credit-applications'
      fullPath: '/admin/credit-applications'
      preLoaderRoute: typeof AuthenticatedAdminCreditApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/credit': {
      id: '/_authenticated/admin/credit'
      path: '/credit'
      fullPath: '/admin/credit'
      preLoaderRoute: typeof AuthenticatedAdminCreditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/purchase-orders_/$poId': {
      id: '/_authenticated/admin/purchase-orders_/$poId'
      path: '/purchase-orders/$poId'
      fullPath: '/admin/purchase-orders/$poId'
      preLoaderRoute: typeof AuthenticatedAdminPurchaseOrdersPoIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing/products': {
      id: '/_authenticated/admin/pricing/products'
      path: '/products'
      fullPath: '/admin/pricing/products'
      preLoaderRoute: typeof AuthenticatedAdminPricingProductsRouteImport
      parentRoute: typeof AuthenticatedAdminPricingRoute
    }
    '/_authenticated/admin/pricing/audit': {
      id: '/_authenticated/admin/pricing/audit'
      path: '/audit'
      fullPath: '/admin/pricing/audit'
      preLoaderRoute: typeof AuthenticatedAdminPricingAuditRouteImport
      parentRoute: typeof AuthenticatedAdminPricingRoute
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminPricingRouteChildren {
  AuthenticatedAdminPricingAuditRoute: typeof AuthenticatedAdminPricingAuditRoute
  AuthenticatedAdminPricingProductsRoute: typeof AuthenticatedAdminPricingProductsRoute
}

const AuthenticatedAdminPricingRouteChildren: AuthenticatedAdminPricingRouteChildren =
  {
    AuthenticatedAdminPricingAuditRoute: AuthenticatedAdminPricingAuditRoute,
    AuthenticatedAdminPricingProductsRoute:
      AuthenticatedAdminPricingProductsRoute,
  }

const AuthenticatedAdminPricingRouteWithChildren =
  AuthenticatedAdminPricingRoute._addFileChildren(
    AuthenticatedAdminPricingRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCreditRoute: typeof AuthenticatedAdminCreditRoute
  AuthenticatedAdminCreditApplicationsRoute: typeof AuthenticatedAdminCreditApplicationsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminDiscountCodesRoute: typeof AuthenticatedAdminDiscountCodesRoute
  AuthenticatedAdminDistributorContactsRoute: typeof AuthenticatedAdminDistributorContactsRoute
  AuthenticatedAdminFlashDealsRoute: typeof AuthenticatedAdminFlashDealsRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRouteWithChildren
  AuthenticatedAdminPurchaseOrdersRoute: typeof AuthenticatedAdminPurchaseOrdersRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSyncRoute: typeof AuthenticatedAdminSyncRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPurchaseOrdersPoIdRoute: typeof AuthenticatedAdminPurchaseOrdersPoIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCreditRoute: AuthenticatedAdminCreditRoute,
  AuthenticatedAdminCreditApplicationsRoute:
    AuthenticatedAdminCreditApplicationsRoute,
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminDiscountCodesRoute: AuthenticatedAdminDiscountCodesRoute,
  AuthenticatedAdminDistributorContactsRoute:
    AuthenticatedAdminDistributorContactsRoute,
  AuthenticatedAdminFlashDealsRoute: AuthenticatedAdminFlashDealsRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRouteWithChildren,
  AuthenticatedAdminPurchaseOrdersRoute: AuthenticatedAdminPurchaseOrdersRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSyncRoute: AuthenticatedAdminSyncRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPurchaseOrdersPoIdRoute:
    AuthenticatedAdminPurchaseOrdersPoIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMyAccountRouteChildren {
  AuthenticatedMyAccountAddressesRoute: typeof AuthenticatedMyAccountAddressesRoute
  AuthenticatedMyAccountCompanyRoute: typeof AuthenticatedMyAccountCompanyRoute
  AuthenticatedMyAccountCreditRoute: typeof AuthenticatedMyAccountCreditRoute
  AuthenticatedMyAccountMembershipRoute: typeof AuthenticatedMyAccountMembershipRoute
  AuthenticatedMyAccountOrdersRoute: typeof AuthenticatedMyAccountOrdersRoute
  AuthenticatedMyAccountPaymentRoute: typeof AuthenticatedMyAccountPaymentRoute
  AuthenticatedMyAccountProfileRoute: typeof AuthenticatedMyAccountProfileRoute
  AuthenticatedMyAccountIndexRoute: typeof AuthenticatedMyAccountIndexRoute
}

const AuthenticatedMyAccountRouteChildren: AuthenticatedMyAccountRouteChildren =
  {
    AuthenticatedMyAccountAddressesRoute: AuthenticatedMyAccountAddressesRoute,
    AuthenticatedMyAccountCompanyRoute: AuthenticatedMyAccountCompanyRoute,
    AuthenticatedMyAccountCreditRoute: AuthenticatedMyAccountCreditRoute,
    AuthenticatedMyAccountMembershipRoute:
      AuthenticatedMyAccountMembershipRoute,
    AuthenticatedMyAccountOrdersRoute: AuthenticatedMyAccountOrdersRoute,
    AuthenticatedMyAccountPaymentRoute: AuthenticatedMyAccountPaymentRoute,
    AuthenticatedMyAccountProfileRoute: AuthenticatedMyAccountProfileRoute,
    AuthenticatedMyAccountIndexRoute: AuthenticatedMyAccountIndexRoute,
  }

const AuthenticatedMyAccountRouteWithChildren =
  AuthenticatedMyAccountRoute._addFileChildren(
    AuthenticatedMyAccountRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMyAccountRoute: typeof AuthenticatedMyAccountRouteWithChildren
  AuthenticatedMyOrdersRoute: typeof AuthenticatedMyOrdersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMyAccountRoute: AuthenticatedMyAccountRouteWithChildren,
  AuthenticatedMyOrdersRoute: AuthenticatedMyOrdersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  HowToOrderRoute: HowToOrderRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PcBuilderRoute: PcBuilderRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingInfoRoute: ShippingInfoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  CreditApplicationSuccessRoute: CreditApplicationSuccessRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
  TrackOrderNumberRoute: TrackOrderNumberRoute,
  CreditApplicationIndexRoute: CreditApplicationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
