// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getFreshAccessToken } from "@/lib/auth-session";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Uses getFreshAccessToken() (not a raw supabase.auth.getSession()) so that a
// stale/expired session never gets attached as a dead Bearer token — see
// src/lib/auth-session.ts for why that used to cause spurious 401s.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const token = await getFreshAccessToken();
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
